const $=s=>document.querySelector(s);let state={};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function table(items,cols){if(!items?.length)return '<div class="empty">Ainda sem dados persistidos. O próximo ciclo autónomo preencherá esta área.</div>';return `<div style="overflow:auto"><table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${items.slice().reverse().slice(0,100).map(x=>`<tr>${cols.map(c=>`<td>${esc(typeof c[1]==='function'?c[1](x):x[c[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderPages(d){
 const nursery=$('#page-nursery');if(nursery)nursery.innerHTML=`<h1>VIVEIRO</h1><p class="muted">Motor autónomo de criação e seleção.</p><div class="cards"><div class="card">Geração<b>#${esc(d.generation)}</b></div><div class="card">Agentes ativos<b>${esc(d.active_agents)}</b></div><div class="card">Capital virtual<b>€${esc(d.capital)}</b></div><div class="card">Modo<b>${esc(d.mode||'LAB')}</b></div></div><h2>Histórico evolutivo</h2>${table(d.history,[['Evento','event'],['Data','at']])}`;
 const st=$('#page-strategies');if(st)st.innerHTML=`<h1>ESTRATÉGIAS</h1><p class="muted">Candidatas geradas e persistidas pelo Viveiro.</p>${table(d.strategy_items||d.strategy_data||[],[['ID','id'],['Estratégia','name'],['Geração','generation'],['Estado','stage'],['Fonte','source']])}`;
 const bt=$('#page-backtests');if(bt)bt.innerHTML=`<h1>BACKTESTS</h1><p class="muted">Resultados históricos usados nos gates de seleção.</p>${table(d.backtest_items||d.backtest_data||[],[['ID','id'],['Estratégia','strategy'],['Fonte','source'],['Estado','stage'],['Resultado',x=>x.result??x.score??'-']])}`;
 const rp=$('#page-reports');if(rp)rp.innerHTML=`<h1>RELATÓRIOS</h1><div class="cards"><div class="card">Estratégias<b>${esc(d.strategies||0)}</b></div><div class="card">Backtests<b>${esc(d.backtests||0)}</b></div><div class="card">Geração<b>#${esc(d.generation||0)}</b></div><div class="card">LIVE<b>${d.live_trading_enabled?'ON':'OFF'}</b></div></div><h2>Eventos recentes</h2>${table(d.history||[],[['Evento','event'],['Data','at']])}`;
}
async function loadViveiro(){try{let r=await fetch('./viveiro_status.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);state=await r.json();document.querySelectorAll('[data-v]').forEach(el=>{let k=el.dataset.v;if(k in state)el.textContent=state[k]});let live=$('#live-state');if(live){live.textContent=state.live_trading_enabled?'LIVE ATIVO':'LAB / LIVE BLOQUEADO';live.className=state.live_trading_enabled?'danger':'status'}let list=$('#task-list');if(list)list.innerHTML=(state.tasks||[]).slice().reverse().map(t=>`<button class="task" data-task="${esc(t.id)}"><b>${esc(t.agent_id||'SYSTEM')}</b><span>${esc(t.type)}</span><small>${esc(t.status)}</small></button>`).join('')||'<p class="muted">Sem tarefas persistidas neste ciclo.</p>';let stamp=$('#updated');if(stamp)stamp.textContent=state.updated_at?'Atualizado '+new Date(state.updated_at).toLocaleString('pt-PT'):'A aguardar primeiro ciclo';let feed=$('#feed-state');if(feed){feed.textContent='● Feed sincronizado';feed.className='status'}renderPages(state)}catch(e){let s=$('#feed-state');if(s){s.textContent='Feed indisponível';s.className='danger'}}}
function go(page){document.querySelectorAll('.nav [data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelectorAll('.page').forEach(x=>x.hidden=true);let p=$('#page-'+page);if(!p){page='office';p=$('#page-office')}p.hidden=false;if(location.hash!=='#'+page)history.replaceState(null,'','#'+page);window.scrollTo({top:0,behavior:'smooth'})}
function popup(title,body){let m=$('#modal');m.querySelector('h2').textContent=title;m.querySelector('p').innerHTML=body;m.showModal()}
document.addEventListener('click',e=>{let nav=e.target.closest('.nav [data-page]');if(nav){e.preventDefault();go(nav.dataset.page);return}let hub=e.target.closest('[data-hub]');if(hub){popup(hub.dataset.hub,'Departamento ativo no pipeline do Viveiro.<br><br>Os resultados persistidos aparecem automaticamente nas páginas Viveiro, Estratégias, Backtests e Relatórios.');return}let task=e.target.closest('[data-task]');if(task){let t=(state.tasks||[]).find(x=>String(x.id)===task.dataset.task);popup('Tarefa '+task.dataset.task,t?`Agente: <b>${esc(t.agent_id||'SYSTEM')}</b><br>Tipo: ${esc(t.type)}<br>Estado: ${esc(t.status)}<br>${esc(t.detail||'')}`:'Detalhe indisponível.');return}let act=e.target.closest('[data-action]');if(act){if(act.dataset.action==='refresh')loadViveiro();else go(act.dataset.action)}});
addEventListener('hashchange',()=>go((location.hash||'#office').slice(1)));go((location.hash||'#office').slice(1));loadViveiro();setInterval(loadViveiro,30000);
